### PR TITLE
Fix Security on Chatbot Routes

### LINKED ISSUE #252: Fix route security on chatbot routes
**Description**

Since basically as long as your logged in, you can ask questions or upload documents into any course.

We probably need to restrict it so that only the helpme backend can call the chatbot routes (probably with some shared API key). This will come with some performance overhead but it's the only way to do it since the chatbot repo does not have access to user or course info

### PR DESCRIPTION
**Pull request by AdamFipke**
# Description

So the problem with the current token system is you just need to be logged in to get a token (and thus call any chatbot endpoint).
So, for example, i could just create an account (and never join any course) and then call the endpoints that delete all chatbot data for all of the courses (because that's an endpoint on the chatbot apparently lol).
So there are no role guards basically, nor any course guards (so i can access documents in questions in courses that i am not in).
So by adding a new chatbot api key (that only the backend of helpme has), users can't just call the chatbot endpoints directly, they have to go through the helpme system first (in which i can use CourseRolesGuard to protect the endpoints)

This also:
- Adjusts/adds more tooltips for helping users around the chatbot
- Cleaned up and consolidated a lot of chatbot types that should be a lot more accurate

Closes #252 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [x] This change requires an addition/change to the production .env variables. These changes are below:

In `/server/.env`:
```
# Needed to make requests to the chatbot service in chatbot repo (needs to match the CHATBOT_API_KEY in the .env in the chatbot repo)
CHATBOT_API_KEY=changemepls
# Change this to the courseId of your "HelpMe" course (used by chatbot when asking system questions)
HELPME_COURSE_ID = 34
```

In Chatbot Repo `.env`
```
# All requests made to the chatbot repo will need this API key (make sure it matches the CHATBOT_API_KEY in the .env in the helpme repo)
CHATBOT_API_KEY=changemepls
```

- [x] This change requires developers to add new .env variables. The file and variables needed are below:

In `/server/.env`:
```
# Needed to make requests to the chatbot service in chatbot repo (needs to match the CHATBOT_API_KEY in the .env in the chatbot repo)
CHATBOT_API_KEY=ForIBecomeBrokeFinancerOfOpenAICalls
# Change this to the courseId of your "HelpMe" course (used by chatbot when asking system questions)
HELPME_COURSE_ID = 
```

In Chatbot Repo `.env`
```
# All requests made to the chatbot repo will need this API key (make sure it matches the CHATBOT_API_KEY in the .env in the helpme repo)
CHATBOT_API_KEY=ForIBecomeBrokeFinancerOfOpenAICalls
```

- [ ] This change requires a database query to update old data on production. This query is below:

# How Has This Been Tested?

So I didn't add many integration tests for this since I basically would have to mock the chatbot api, which means the only things I would really be testing for is whether the guards are working. And tbh I want to gamble that spending the time to make a bunch of tests just to check the roles guard isn't going to save much maintenance time (if any time) in the future. And I'm very confident that I implemented the guard correctly on each of the endpoints since I have made various courseRolesGuards. Or in short, I guess ~~I'm just lazy~~ there's just a lot of work to be done and this is not a priority right now.

I did manually test each route though, and also tested if the CourseRolesGuard worked.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any work that this PR is dependent on has been merged into the main branch
- [ ] Any UI changes have been checked to work on desktop, tablet, and mobile

### CODE REVIEW

File: packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx [hunk 1]
```diff
@@ -281,32 +243,6 @@ const Chatbot: React.FC<ChatbotProps> = ({
     setInput('')
   }
 
-  const getSourceLinkButton = (
```
Comment (AdamFipke) [inline packages/frontend/app/(dashboard)/course/[cid]/components/chatbot/Chatbot.tsx:284]: oh yeah so "getSourceLinkButton" was basically a react component so I renamed it for clarity.

But that's small. A bad thing here was that this component was defined inside the body of another component (nested component definitions), which will mean that all getSourceLinkButtons will always do a full unmount and re-mount every time there's a re-render of the outer Chatbot component (for example, it would completely unmount and remount every time the user types something in the text box).
It's mentioned here in the React docs: https://react.dev/learn/preserving-and-resetting-state
