### PR TITLE
fix(invite): add option to decline course invitation (#273)

### LINKED ISSUE #273: [Small] Invite page -> No thanks (takes to /courses)
This would just be a simple addition to add a button on the invite page that takes you to /courses.

*Usually* if you are on the invite page, you almost always want to accept the invite. But sometimes cookies will be set and you will just be taken to it by accident and so you might want an option to just say "no thanks"

### PR DESCRIPTION
**Pull request by Akshat-Kalra**
# Description

Fixes Issue #273
 
Adds a "Decline Invitation Button" to the invite page taking the user back to the `/courses` route.

Achieved by adding 2 optional (`secondaryButtonLabel` and `secondaryButtonAction`) props to the  `InviteCard` component which only renders if both the label and the action is provided.

No new dependencies required

Closes #273 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This change requires an addition/change to the production .env variables. These changes are below:
- [ ] This change requires developers to add new .env variables. The file and variables needed are below:
- [ ] This change requires a database query to update old data on production. This query is below:

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

I logged in with an account with no courses and with the UBCO Organization, then went to `/invite?cid=37&code=invite-code` route on localhost, which is the invite link for CS 304 in the UBCO Org, then manually tested it.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any work that this PR is dependent on has been merged into the main branch
- [x] Any UI changes have been checked to work on desktop, tablet, and mobile

### CODE REVIEW

File: packages/frontend/app/invite/page.tsx [hunk 1]
```diff
@@ -150,6 +150,10 @@ export default function CourseInvitePage(): ReactElement {
                 }
                 await addStudent(userData)
               }}
+              secondaryButtonLabel="Decline Invitation"
+              secondaryButtonAction={() => {
+                router.push('/courses')
+              }}
```
Comment (AdamFipke) [inline packages/frontend/app/invite/page.tsx:156]: *technically* speaking putting routing actions inside an onClick like this isn't recommended (for webcrawlers like for SEO, and I believe it might impact accessibility) and instead the button should have an `href` attribute, but meh I don't think it would matter that much in this case (since we don't need SEO and since it's still a Button and not like a div it should still be fairly obvious for screen readers)

**Review by AdamFipke — APPROVED** [review]

File: packages/frontend/app/invite/page.tsx (hunk 1 above)
Comment (AdamFipke) [reply packages/frontend/app/invite/page.tsx:156]: Oh and I guess one more thing that's related that I should mention. Next.js's `<Link>` component could also be used to wrap an antd Button, that way it takes advantage of the fancy Next.js things (most notably being prefetching the /courses page before the user clicks on it). 

Not that I think that change really needs to be made since it's rare that this would be clicked on, but something i'd just thought might be a useful thing for future :)
