### PR TITLE
Fixed pagination for Organization Users table

### LINKED ISSUE #441: Organization Users table is showing incorrect number of pages
**Description**

The `UsersTable.tsx` and its associated endpoint (`@Get(':oid/get_users{/:page}')`) does not show/handle the total number of users (see below)

Image

The endpoint needs to be modified to return the total number of users *in addition to* the 50 (or less) users for that page (the return-type for the endpoint will need to be modified).

The query inside `getUsers()` inside organiztion.service will need to be updated to include the COUNT (or perhaps make a seperate query by doing `OrganizationUser.count({orgId})` kinda thing)

### PR DESCRIPTION
**Pull request by mahigangal**
# Description

The Organization Users table now returns and displays the real total user count. Pagination displays only the actual number of pages, and the Next/Previous controls are enabled only when multiple pages are available. Each page shows up to 50 users. Previously, the total was hardcoded to 5000, which created ~100 phantom pages.

Backend `@Get(':oid/get_users{/:page}')` now uses `getManyAndCount()` to return both the paginated users and the total count, instead of relying on a fixed total. The frontend `UsersTable` now reads `response.total` and passes it to the Pagination component, so page counts and Next/Previous controls accurately reflect the total. Each page still shows up to 50 users.

Screenshot 2026-01-12 at 11 24 02 PM

Closes #441 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This change requires an addition/change to the production .env variables. These changes are below:
- [ ] This change requires developers to add new .env variables. The file and variables needed are below:
- [ ] This change requires a database query to update old data on production. This query is below:

# How Has This Been Tested?

Manual Tests: The maximum number of users that can be displayed on a single page is 50. Right now, there are only 6 users in the system; therefore, the system only shows one page with the Next arrow disabled. I tested the functionality by temporarily setting the maximum number of users that can be displayed on a single page to 5. In this case, I could visit page 1 (showing 5 users) and page 2 (showing 1 user) using the Next and Previous arrows. When multiple pages get created, 'Go to _ page' is visible and works to go to a specific page. 

Unit tests (organization.service.spec.ts): Updated assertions to expect {users, total} structure instead of just users array

organization.integration.ts.snap: Updated snapshot to match new API response format with total count

# Checklist:

- [x] I have performed a code review of my own code (under the "Files Changed" tab on github) to ensure nothing is committed that shouldn't be (e.g. leftover `console.log`s, leftover unused logic, or anything else that was accidentally committed)
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing tests pass *locally* with my changes
- [x] Any work that this PR is dependent on has been merged into the main branch
- [ ] Any UI changes have been checked to work on desktop, tablet, and mobile

### CODE REVIEW

File: packages/server/src/organization/organization.controller.ts [hunk 1]
```diff
@@ -1431,9 +1431,8 @@ export class OrganizationController {
     @Param('oid', ParseIntPipe) oid: number,
     @Param('page', ParseIntPipe) page: number,
     @Query('search') search: string,
-  ): Promise<OrgUser[]> {
+  ): Promise<{ users: OrgUser[]; total: number }> {
```
Comment (bhunt02) [inline packages/server/src/organization/organization.controller.ts]: use the DTO class you wrote in common/index.ts

File: packages/server/src/organization/organization.service.ts [hunk 2]
```diff
@@ -185,58 +185,42 @@ export class OrganizationService {
...
-      const likeSearch = `%${search.replace(' ', '')}%`.toUpperCase();
+      const likeSearch = `%${search.replace(/\s+/g, '').toUpperCase()}%`;
+
       organizationUsers.andWhere(
-        new Brackets((q) => {
-          q.where('UPPER("UserModel".name) like :searchString', {
-            searchString: likeSearch,
-          });
-        }),
+        `UPPER(CONCAT(user.firstName, user.lastName)) LIKE :search`,
```
Comment (bhunt02) [inline packages/server/src/organization/organization.service.ts]: did you make sure to test the search out, btw? i'm getting some red flags - postgres requires quotations around camel case properties and typeorm qb doesnt always infer

Comment (mahigangal) [reply packages/server/src/organization/organization.service.ts]: Thank you for pointing this out. I have fixed this query with `UPPER(REPLACE(user.name, ' ', '')) LIKE :search` to use the database name column, instead of raw concatenation. I am also removing the spaces from both the search input and the name column to ensure matching. 

I tested the search, and it is working with all edge cases I could think of. Please let me know if there are still any red flags.

File: packages/server/src/organization/organization.service.ts [hunk 3]
```diff
@@ -185,58 +185,42 @@ export class OrganizationService {
...
-        UserModel,
-        'UserModel',
-        'UserModel.id = OrganizationUserModel.userId',
-      )
-      .where('OrganizationUserModel.organizationId = :organizationId', {
+  ): Promise<{ users: OrgUser[]; total: number }> {
+    const organizationUsers = OrganizationUserModel.createQueryBuilder(
+      'orgUser',
+    )
+      .leftJoinAndSelect('orgUser.organizationUser', 'user')
```
[the remark this answers is not in the document]
Comment (bhunt02) [reply packages/server/src/organization/organization.service.ts]: had a feeling...

**Review by bhunt02 — APPROVED** [review]
i'd wait for adam's review, but after addressing comments nothing jumps out as problematic to me

**Review by AdamFipke — CHANGES_REQUESTED** [review]
meant to request changes my bad

**Review by AdamFipke — APPROVED** [review]
tested it with the new search, looks to work good!
