### PR TITLE
Tablet Navbar issues fixed

### LINKED ISSUE #418: Better Tablet Navbar
Right now, the hamburger menu will show itself only at the `md` breakpoint (like 400 something px)

This poses a problem, where even browser widths as high as 1200px will start to show a horizontal scrollbar because all of the nav elements cannot fit horizontally (though I should note that this is only really bad for professors since they have the Course Settings and Insights nav elements ontop of everything else)

Image

This horizontal scroll also messes up the profile dropdown menu (since it goes off of viewport width, unfortunately)

Image

---

### Solution

Make it so the navbar will go into the mobile "hamburger" menu mode whenever all nav elements cannot fit. Note that this width is very dynamic, since there can be a different number of nav elements depending on whether the user is a student or professor or depending on what course features the course has enabled 

ALSO, we could add an intermediary step (between "hamburger" menu mode and the full desktop navbar) where the paddings of the nav elements are reduced in an effort to fit more nav elements in without needing to fully go to the hamburger menu.

### PR DESCRIPTION
**Pull request by mahigangal**
# Description

This PR fixes the responsive course header behavior for issue #418. Previously, the header switched to the drawer menu only at a fixed breakpoint (768px). On tablet/smaller desktop widths, role/course-dependent nav items (especially professor links like Course Settings and Insights) could overflow, causing a horizontal scrollbar and dropdown placement issues.

The header now uses a 3-mode system:
- desktop
- compact (reduced top-level nav padding)
- drawer (hamburger)

Mode selection is based on measured rendered width (not fixed nav-item-count estimates), so it helps with student vs professor nav differences, enabled course features, zoom/larger font size scenarios.

Additionally, NavigationMenu now supports an optional showViewport prop so hidden measurement navbars can skip rendering an extra viewport element.

No dependencies, env changes, DB changes, or install steps are required.

Closes #418 

## Screenshots

1. Professor course at ~1024px
Screenshot 2026-03-05 at 3 56 56 PM

2. Professor course at ~1280px
Screenshot 2026-03-05 at 3 57 53 PM

3. Student course at ~1024px
Screenshot 2026-03-05 at 3 59 41 PM

4. Narrow tablet width ~820px (student or professor)
Screenshot 2026-03-05 at 4 01 07 PM

5. Queues dropdown near a threshold width (~820px)
Screenshot 2026-03-05 at 4 01 49 PM

6. Profile dropdown near a threshold width (~1024px)
Screenshot 2026-03-05 at 4 02 45 PM

All screenshots show no horizontal scrollbar and correct nav mode for width/role.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`
- [ ] This change requires an addition/change to the production .env variables. These changes are below:
- [ ] This change requires developers to add new .env variables. The file and variables needed are below:
- [ ] This change requires a database query to update old data on production. This query is below:

# How Has This Been Tested?

Manually tested on course pages with different roles and feature sets, focusing on widths where overflow previously occurred.

Repro steps:

1. Open a student course home page and a professor course home page.
2. Resize viewport across tablet/smaller desktop widths (for example around 820px, 1024px, 1280px).
3. Verify the header switches between desktop, compact, and drawer based on fit.
4. Confirm there is no horizontal scrollbar.
5. Open the profile dropdown and queue dropdown near threshold widths and verify positioning/interaction.
7. Repeat checks at browser zoom levels (125%, 150%) and confirm nav switches mode instead of overflowing.

Zoom testing note: I could only test zoom reliably at desktop width. At 100% zoom, all nav elements are shown in desktop mode; after zooming in enough, the navbar shifts to drawer mode without introducing a horizontal scrollbar.  I couldn’t reliably test zoom at other widths in DevTools device mode.

# Checklist:

- [x] I have performed a code review of my own code (under the "Files Changed" tab on github) to ensure nothing is committed that shouldn't be (e.g. leftover `console.log`s, leftover unused logic, or anything else that was accidentally committed)
- [x] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing tests pass *locally* with my changes
- [x] Any work that this PR is dependent on has been merged into the main branch
- [x] Any UI changes have been checked to work on desktop, tablet, and mobile

### CODE REVIEW

File: packages/frontend/app/components/HeaderBar.tsx [hunk 1]
```diff
@@ -595,10 +643,18 @@ const NavBar = ({
...
  */
+
+type NavMode = 'desktop' | 'compact' | 'drawer'
+
 const HeaderBar: React.FC = () => {
   const { userInfo } = useUserInfo()
   const [isDrawerOpen, setIsDrawerOpen] = useState(false)
-  const isDesktop = useMediaQuery('(min-width: 768px)')
+  const [navMode, setNavMode] = useState<NavMode>('drawer')
+  const isPhone = useMediaQuery('(max-width: 640px)')
```
Comment (AdamFipke) [inline packages/frontend/app/components/HeaderBar.tsx]: you *might* want to leave this as 768px instead of 640px since basically the entire site uses `md:` as the breakpoint between mobile and desktop for CSS, so in the case where the browser width is at 700px it might show the desktop navbar but with mobile styles.

File: packages/frontend/app/components/HeaderBar.tsx [hunk 2]
```diff
@@ -633,104 +689,192 @@ const HeaderBar: React.FC = () => {
...
+    nodes.forEach((node) => observer.observe(node))
+    updateNavMode()
+
+    return () => observer.disconnect()
+  }, [updateNavMode, pathname, course, userInfo])
+
+  return (
+    <div ref={availableWidthRef} className="relative w-full">
+      <div className="pointer-events-none invisible absolute left-0 top-0 -z-10 h-0 overflow-hidden">
+        <div ref={regularMeasureRef} className="w-max">
```
Comment (AdamFipke) [inline packages/frontend/app/components/HeaderBar.tsx]: Okay I get this now. 

We're rendering 3 navbar components all the time.

2 of these navbar components are invisible and literally only exist so their width can be measured. 1 navbar has the condensed classnames, and the other the standard desktop navbar.

The final navbar is the real one.

It's kinda creative, but I think rendering 3 navbars might have some performance cost considerations that might not be worth itt so I might wait on merging this in case someone thinks of a better solution.

**Review by AdamFipke — CHANGES_REQUESTED** [review]
See comments. 

Rendering 3 navbars and using 2 of them just for measuring the width of the desktop navbar and condensed navbar to determine what mode the true navbar should be in is a creative approach, but I'm unsure if it'll be worth the performance cost. I will leave this to you to test more. Maybe one of us can come up with another way that's better for performance if it turns out to be noticeably hurting performance. 

Check out React Dev Tools and see if there's lots of unnecessary re-renders. Also try using chrome dev tools to throttle performance and see if it stills feels responsive.

Image

File: packages/frontend/app/components/HeaderBar.tsx [hunk 3]
```diff
@@ -633,104 +689,192 @@ const HeaderBar: React.FC = () => {
...
+      setNavMode('compact')
+      return
+    }
+
+    setNavMode('drawer')
+  }, [isPhone])
+
+  useLayoutEffect(() => {
+    updateNavMode()
+  }, [updateNavMode, pathname, course, userInfo])
```
[the remark this answers is not in the document]
Comment (AdamFipke) [reply packages/frontend/app/components/HeaderBar.tsx]: Huh, so I went and manually tested it and maybe this is less performance intensive than I thought? Like it really does only trigger the re-render at the breakpoints. Moving the window width a lot doesn't seem to cause any re-renders. So maybe debouncing isn't really that necessary.
image

Although I guess this only shows the visible navbar. The invisible ones would also be re-rendering a bunch.

**Review by AdamFipke — COMMENTED** [review]
just one small comment, should be good to merge after

**Review by AdamFipke — APPROVED** [review]

File: packages/frontend/app/components/HeaderBar.tsx [hunk 4]
```diff
@@ -350,45 +400,47 @@ const NavBar = ({
...
                         Schedule
                       </Link>
                     </NavigationMenuItem>
                   )}
                   {(role === Role.TA || role === Role.PROFESSOR) && (
-                    <NavigationMenuItem
-                      className={
-                        isACourseSettingsPage
-                          ? // the hover:border-none is because the inner link has a hover effect that adds another border
-                            'md:border-helpmeblue bg-zinc-300/80 md:border-b-2 md:bg-white md:hover:border-none md:focus:border-none'
```
Comment (AdamFipke) [inline packages/frontend/app/components/HeaderBar.tsx:370]: I tried `ctrl+f`ing "border-helpmeblue" and I see that the original desktop styles have actually been completely removed (presumably got misinterpreted for some reason after my first round of feedback). I was expecting that the changes were at least tested. I'll look into fixing it, but I might just revert the changes done by this PR

Comment (AdamFipke) [reply packages/frontend/app/components/HeaderBar.tsx:370]: Yeah, the more I look at it now, the more random broken changes I see. It's not worth my time to try to salvage this.
